### ISSUE TITLE
Story - Representative Model Page

### ISSUE THREAD

**Issue by bzsinger** [WeTheSWEople/SWEThePeople#100]
Create a representative model page that includes:
- [ ] a grid of at least **9** representatives
- [ ] at least three attributes for each representative
- [ ] links to each instance

**Time**
Estimated - 2hr
Actual - Xhrs

**Comment by palakhirpara** [comment]
Pull all of the 435 reps!

**Comment by bzsinger** [comment]
Closed by #125
