### ISSUE TITLE
Story - Beautify/Reorganize Representative and Party Detail Pages

### ISSUE THREAD

**Issue by bzsinger** [WeTheSWEople/SWEThePeople#105]
- [ ] Reorganize data

Embed more:
- [ ] Images
- [ ] Video
- [ ] Maps
- [ ] Social Media feeds

Add more:
- [ ] Information
- [ ] External links

**Time**
Estimated - 10hr
Actual - Xhr

**Comment by MTirtowidjojo** [comment]
This was completed.
