### ISSUE TITLE
Story - Backend Code Tests

### ISSUE THREAD

**Issue by bzsinger** [WeTheSWEople/SWEThePeople#112]
Write backend code tests using:
- [X] unittest

**Time**
Estimated - 5hr
Actual - 7hr

**Comment by bzsinger** [comment]
Closed by https://github.com/WeTheSWEople/SWEThePeople/commit/605e27ad58d5f592f14a6ef093a71f94c3d90cd5

**Comment by bzsinger** [comment]
@palakhirpara @copperstick6 Did you guys add the unit test count to the about page?

**Comment by copperstick6** [comment]
No, @MTirtowidjojo gracefully did it for us.
