### ISSUE TITLE
Build 3 pages for Representatives

### ISSUE THREAD

**Issue by MTirtowidjojo** [WeTheSWEople/SWEThePeople#16]
- one for each instance
- data
- external links
- embedded images (e.g. Bing, Flickr, Google)
- embedded videos (e.g. Bing, Google, Vimeo)
- embedded maps (e.g. Google Maps)
- embedded social network feeds (e.g. Facebook, Twitter)
- links to Political Parties Model
- links to Legislative District Model

**Comment by bzsinger** [comment]
Majority Leader, Minority Leader, Speaker

**Comment by MTirtowidjojo** [comment]
Attributes:
- Name
- Gender
- Age
- Number of terms

**Comment by bzsinger** [comment]
References #70

**Comment by bzsinger** [comment]
Closed by #82
