### ISSUE TITLE
Story - Add search implementation

### ISSUE THREAD

**Issue by bzsinger** [WeTheSWEople/SWEThePeople#167]
- [x] Set attributes to search elements by
	- Set attributes for 
		- [x] Representatives
		- [x] Parties
		- [x] Districts
- [x] Add search mechanism
- [x] Searching must be Google-like and handle many terms

**Time**
Estimated - 8hrs
Actual - 10hrs

**Comment by MTirtowidjojo** [comment]
Took 10 hours to complete.

**Comment by bzsinger** [comment]
Closed by #211
