### ISSUE TITLE
Build 3 pages for Political Parties Model

### ISSUE THREAD

**Issue by MTirtowidjojo** [WeTheSWEople/SWEThePeople#17]
- one for each instance
- data
- external links
- embedded images (e.g. Bing, Flickr, Google)
- embedded videos (e.g. Bing, Google, Vimeo)
- embedded maps (e.g. Google Maps)
- embedded social network feeds (e.g. Facebook, Twitter)
- links to Representatives Model
- links to Legislative Districts Model

**Comment by MTirtowidjojo** [comment]
Attributes:
- Name
- National Committee chair
- Formation date
- Color

**Comment by bzsinger** [comment]
References #70

**Comment by bzsinger** [comment]
Closed by #84
