### ISSUE TITLE
Build 3 pages for Legislative Districts Model

### ISSUE THREAD

**Issue by MTirtowidjojo** [WeTheSWEople/SWEThePeople#18]
- one for each instance
- data
- external links
- embedded images (e.g. Bing, Flickr, Google)
- embedded videos (e.g. Bing, Google, Vimeo)
- embedded maps (e.g. Google Maps)
- embedded social network feeds (e.g. Facebook, Twitter)
- links to Representatives Model
- links to Political Parties Model

**Comment by MTirtowidjojo** [comment]
Attributes:
- State
- Population
- Voting population
- Median income

**Comment by bzsinger** [comment]
**Majority Leader:** Kevin McCarthy, CA-23
**Minority Leader:** Nancy Pelosi, CA-12
**Speaker:** Paul Ryan, WI-1

**Comment by bzsinger** [comment]
References #73

**Comment by bzsinger** [comment]
Closed by [Downing](https://piazza.com/class/jcgrhy8wgynfk?cid=176)
