### ISSUE TITLE
Auto-deployment pipeline from master branch to ec2 instance

### ISSUE THREAD

**Issue by copperstick6** [WeTheSWEople/SWEThePeople#2]
Figure out how to auto deploy to ec2 via a deployment pipeline

**Comment by copperstick6** [comment]
This is a long term goal. We don't expect to have this done soon. A useful article is [here](https://aws.amazon.com/blogs/devops/automatically-deploy-from-github-using-aws-codedeploy/)

**Comment by bzsinger** [comment]
References #77
