### ISSUE TITLE
Remove old photos to reduce repo size

### ISSUE THREAD

**Issue by MTirtowidjojo** [WeTheSWEople/SWEThePeople#210]

**Comment by copperstick6** [comment]
@palakhirpara and I have been talking about perhaps just stuffing everything into a public S3 bucket and directly accessing the S3 bucket for the image. We might be able to organize the images such that it follows a recognizable pattern so that we don't have to amend our database.

**Comment by palakhirpara** [comment]
We also need to prune the .git folder

**Comment by palakhirpara** [comment]
Closing this. Need to prune .git folder to reduce the repo size
