### ISSUE TITLE
Add highlighting to the search page

### ISSUE THREAD

**Issue by MTirtowidjojo** [WeTheSWEople/SWEThePeople#214]

**Comment by palakhirpara** [comment]
we can use this [https://www.npmjs.com/package/react-text-highlighter]

**Comment by MTirtowidjojo** [comment]
That's a great suggestion!  Palak you are fantastic!

**Comment by palakhirpara** [comment]
I found a better npm package https://www.npmjs.com/package/react-highlighter

**Comment by MTirtowidjojo** [comment]
That's an even better suggestion Palak!

**Comment by MTirtowidjojo** [comment]
Closed for real this time by 0ab85afafb3471b3b22b1a1a95f77ac4c966d274
