### ISSUE TITLE
Create basic About page

### ISSUE THREAD

**Issue by bzsinger** [WeTheSWEople/SWEThePeople#22]

**Comment by copperstick6** [comment]
#23 creates a separate About component and has basic work with a basic GET request to a singular endpoint. Need to implement promises/asynchronous batch requests and processing.

**Comment by copperstick6** [comment]
I think we're blocked by #6 on this one as well. We need to make sure templating is good to go, but we can start working on the requests and state management for returned data

**Comment by bzsinger** [comment]
Closed by merge

**Comment by bzsinger** [comment]
References #75
