### ISSUE TITLE
Story - Parties without chairmen

### ISSUE THREAD

**Issue by NealFM** [WeTheSWEople/SWEThePeople#257]
As a user, when sorting by chair name on the parties page, remove result of parties without chairmen.

**Comment by NealFM** [comment]
Half of the first page when sorted ASC are parties without chair and not actual names of chairs. 
![no-party-chair](https://user-images.githubusercontent.com/15219698/38586328-f565f474-3ce2-11e8-826e-42d287785b39.PNG)

**Comment by bzsinger** [comment]
@MTirtowidjojo Sorting issue or model setup issue?

**Comment by MTirtowidjojo** [comment]
@bzsinger it's an issue with sorting on the backend. We can either choose to sort them to the end of the list or remove them completely what do you think?
