### ISSUE TITLE
Story - Demographics

### ISSUE THREAD

**Issue by NealFM** [WeTheSWEople/SWEThePeople#260]
As a user from Texas, I'd like to see demographics for hispanic/latino in the graphs instead of a sizable "Some other race" category. 

---

**Time**:
Estimated: 8hr
Actual: Xhr

**Comment by bzsinger** [comment]
@raulcodes @palakhirpara The new Census scrapers gets this information – it collects it under "ethnicity" instead of "race"

**Comment by bzsinger** [comment]
Somewhat related to #262 if we're doing the full redesign
