### ISSUE TITLE
Story - Representative Data

### ISSUE THREAD

**Issue by NealFM** [WeTheSWEople/SWEThePeople#265]
As a user, I'd want to see representative data - how much of the popular vote did they receive within district?

**Comment by bzsinger** [comment]
@palakhirpara @minwoo0jo Does ProPublica/GovTrack make this information readily available?

**Comment by palakhirpara** [comment]
@NealFM  This data is not readily available by our current sources. Is there anything else we can add instead?

**Comment by palakhirpara** [comment]
We added relevant articles instead. Closing Issue.

**Comment by bzsinger** [comment]
Story clarified: add more information, not necessarily popular vote
