### ISSUE TITLE
Add your bio for the about page on here

### ISSUE THREAD

**Issue by MTirtowidjojo** [WeTheSWEople/SWEThePeople#34]
Comment on this issue with the bio you want to appear for you on the About page.

**Comment by MTirtowidjojo** [comment]
Michael is a third-year CS student who trains in Taekwondo and enjoys reading World War II stories.

**Comment by palakhirpara** [comment]
Palak is a senior who will be graduating this semester with BSCS and likes watching cricket.

**Comment by bzsinger** [comment]
References #75
