### ISSUE TITLE
Integrate Bootstrap with project

### ISSUE THREAD

**Issue by copperstick6** [WeTheSWEople/SWEThePeople#6]
Add Bootstrap to our react project

**Comment by bzsinger** [comment]
@raulcodes @copperstick6 This is done, right?

**Comment by copperstick6** [comment]
I don't think we need to worry about this too much at this moment unless @raulcodes thinks differently

**Comment by raulcodes** [comment]
My navbar pr integrated bootstrap already

**Comment by bzsinger** [comment]
References #77
