### ISSUE TITLE
Story - About Page

### ISSUE THREAD

**Issue by bzsinger** [WeTheSWEople/SWEThePeople#75]
Includes:
- [X] a description of the site, its purpose, its intended users
- [ ] an explanation of the interesting result of integrating disparate data
- [X] the group name
- [X] the group members
- [X] for each member - name, photo, bio, major responsibilities, no. of commits, no. of issues, no. of unit tests
- [X] stats - total no. of commits, total no. of issues, total no. of unit tests
- [x] data - links to the data sources, description of how each was scraped
- [x] tools - tools used, describe their use, special focus on optional tools that were not required
- [x] a link to the GitBook report
- [X] a link to the GitHub repo

**Time**
Estimated - 1hrs
Actual - 2hrs +

**Comment by copperstick6** [comment]
The About page took slightly longer, because we put more focus on the other pages, so we ended up taking more time making up for the lost technical capital earlier.

**Comment by minwoo0jo** [comment]
Although it is correct for now, the issue count will need to start looping through pages once we have more than 100
