### ISSUE TITLE
Story - Critiques

### ISSUE THREAD

**Issue by bzsinger** [WeTheSWEople/SWEThePeople#76]
Self-critique:
- [x] What did we do well?
- [x] What did we learn?
- [x] What can we do better?
- [x] What puzzles us?

Other-critique:
- [x] What did they do well?
- [x] What did we learn from their api / website?
- [x] What can they do better?
- [x] What puzzles us about their api / website?

**Time**
Estimated - 2hrs
Actual - 1 hrs

**Comment by palakhirpara** [comment]
Closed by [Critiques](https://wethesweople.gitbooks.io/report/self-critique.html)
