### ISSUE TITLE
Story - Setup/Deployment

### ISSUE THREAD

**Issue by bzsinger** [WeTheSWEople/SWEThePeople#77]
Build and deploy basic website, including
- [X] create EC2 instance
- [X] configure instance to allow external traffic using NGINX
- [X] route traffic to go to specific port on local server, run application on that port
- [X] route website traffic to EC2 instance
- [X] integrate Bootstrap
- [X] Create repo README 

**Time**
Estimate: 2hrs
Actual: 4hrs

**Comment by palakhirpara** [comment]
Site up and running. Closed [By](http://swethepeople.me/)
