### ISSUE TITLE
Story - Write Technical Report

### ISSUE THREAD

**Issue by bzsinger** [WeTheSWEople/SWEThePeople#78]
Technical Report:
- [x] motivation
- [x] use cases
- [x] RESTful API
- [x] models
- [x] tools
- [x] hosting
- [x] format the report clearly, attractively, and consistently, using good sections, multiple pages, good headers, figures, and grammar
- [x] use Grammarly
Estimated: 4 hrs
Actual: 4 hrs

**Comment by palakhirpara** [comment]
Closed By [Technical Report](https://wethesweople.gitbooks.io/report/)
