### ISSUE TITLE
Switch from district photo to geojson files

### ISSUE THREAD

**Issue by bzsinger** [WeTheSWEople/SWEThePeople#86]
See:
https://github.com/unitedstates/districts
https://gist.github.com/stereobooster/13a26188d4ad5382bc6da9ffe76ce3e1#file-1-react-google-maps-md
https://github.com/PaulLeCam/react-leaflet

References #73

**Comment by raulcodes** [comment]
Something we should consider here is the fact that we would be rendering ~50 maps on AllDistricts page, which slowed my local build a lot. We could explore other options if we still want to replace the district photos. But, the pr I was about to open adds a map to the individual state page.

<img width="1207" alt="screen shot 2018-02-15 at 7 16 37 pm" src="https://user-images.githubusercontent.com/10414043/36289274-c7fbeddc-1284-11e8-9c10-27e23aef6240.png">

**Comment by bzsinger** [comment]
@raulcodes I think that would be a good idea. Do you think we should also have a district map on the individual district page?

**Comment by palakhirpara** [comment]
For the future: I would say instead of an district map image we should have an actual map ex: embedded google maps

**Comment by bzsinger** [comment]
Resolved by https://github.com/WeTheSWEople/SWEThePeople/commit/f482d54be17147895b1b5acfcf0b92ff889cefd3
