### ISSUE TITLE
Add data for one more state

### ISSUE THREAD

**Issue by palakhirpara** [WeTheSWEople/SWEThePeople#89]
Add data of one more state so that we can have 3 instance for the districts tab in order to meet the phase 1 requirements (3 instances for each model)

**Comment by bzsinger** [comment]
Aren't we doing districts as the model, not states?

**Comment by palakhirpara** [comment]
How are you gonna explains this to the grader? They will probably think we are doing states and see that we only have two instances

**Comment by MTirtowidjojo** [comment]
Closed by PR #91
